[workspace]

members = [
    "zopatract_common",
    "zopatract_core",
    "zopatract_cli",
    "zopatract_fs_resolver",
    "zopatract_stdlib",
    "zopatract_abi",
    "zopatract_test",
    "zopatract_core_test",
]

exclude = ["zopatract_js"]
